// Code generated by goyacc -o gos.go -p Gos -l gos.y. DO NOT EDIT.

package compiler

import __yyfmt__ "fmt"

import (
	"github.com/vc2402/go-script/runtime"
)

type GosSymType struct {
	yys  int
	val  string
	vals []string
	fn   *function
	//	functions []*function
	args         []*varDef
	arg          *varDef
	File         File
	statement    *statement
	statements   []*statement
	typeRef      *typeRef
	lvalue       *lvalue
	lvList       []*lvalue
	constant     *constant
	expression   *expression
	arrayAccess  *arrayAccess
	fieldAccess  *fieldAccess
	expressions  []*expression
	funcCall     *funcCall
	varDef       *varDef
	assignment   *assignment
	fileContents []any
	ifStatement  *ifStatement
	forStatement *forStatement
	methodCall   *methodCall
}

const IDENT = 57346
const INT = 57347
const FLOAT = 57348
const CHAR = 57349
const STRING = 57350
const BOOL = 57351
const FUNCNAME = 57352
const LOR = 57353
const REM = 57354
const LAND = 57355
const GT = 57356
const LT = 57357
const EQ = 57358
const NEQ = 57359
const GTE = 57360
const LTE = 57361
const INC = 57362
const DEC = 57363
const DEFINE = 57364
const ELLIPSIS = 57365
const VAR = 57366
const FUNC = 57367
const PACKAGE = 57368
const MAP = 57369
const IF = 57370
const ELSE = 57371
const SWITCH = 57372
const CASE = 57373
const FOR = 57374
const BREAK = 57375
const CONTINUE = 57376
const RANGE = 57377
const RETURN = 57378
const MAKE = 57379

var GosToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"INT",
	"FLOAT",
	"CHAR",
	"STRING",
	"BOOL",
	"FUNCNAME",
	"'+'",
	"'-'",
	"LOR",
	"'*'",
	"'/'",
	"REM",
	"LAND",
	"GT",
	"LT",
	"EQ",
	"NEQ",
	"GTE",
	"LTE",
	"'!'",
	"INC",
	"DEC",
	"DEFINE",
	"'{'",
	"'}'",
	"'='",
	"'['",
	"']'",
	"','",
	"'.'",
	"'('",
	"')'",
	"';'",
	"':'",
	"ELLIPSIS",
	"VAR",
	"FUNC",
	"PACKAGE",
	"MAP",
	"IF",
	"ELSE",
	"SWITCH",
	"CASE",
	"FOR",
	"BREAK",
	"CONTINUE",
	"RANGE",
	"RETURN",
	"MAKE",
}

var GosStatenames = [...]string{}

const GosEofCode = 1
const GosErrCode = 2
const GosInitialStackSize = 16

var GosExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 3,
	37, 48,
	-2, 2,
	-1, 27,
	27, 72,
	30, 72,
	33, 72,
	-2, 96,
	-1, 43,
	37, 48,
	-2, 3,
	-1, 73,
	37, 51,
	-2, 67,
	-1, 185,
	36, 26,
	-2, 24,
}

const GosPrivate = 57344

const GosLast = 422

var GosAct = [...]uint8{
	15, 106, 11, 136, 135, 9, 127, 12, 128, 75,
	18, 28, 144, 20, 5, 119, 167, 159, 7, 118,
	191, 152, 66, 69, 76, 68, 77, 190, 72, 21,
	189, 155, 159, 157, 178, 158, 156, 155, 115, 65,
	154, 79, 80, 49, 67, 48, 81, 81, 27, 153,
	82, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 81, 108, 27, 82, 27, 92, 113,
	87, 108, 114, 90, 116, 33, 36, 37, 38, 39,
	40, 41, 121, 112, 76, 76, 185, 129, 27, 130,
	86, 110, 91, 124, 125, 26, 141, 89, 110, 20,
	111, 84, 173, 109, 83, 119, 25, 85, 76, 27,
	109, 19, 84, 110, 142, 21, 146, 140, 85, 22,
	150, 175, 143, 23, 42, 109, 139, 20, 147, 148,
	126, 33, 36, 37, 38, 39, 40, 41, 88, 160,
	76, 47, 122, 63, 122, 164, 3, 165, 123, 161,
	163, 43, 166, 129, 162, 108, 129, 33, 170, 168,
	172, 108, 149, 174, 169, 33, 36, 37, 38, 39,
	40, 41, 24, 177, 181, 184, 138, 186, 183, 187,
	42, 188, 110, 17, 105, 26, 134, 107, 110, 20,
	105, 137, 193, 133, 109, 132, 25, 131, 45, 78,
	109, 19, 8, 117, 1, 21, 73, 13, 10, 22,
	30, 62, 27, 23, 42, 33, 36, 37, 38, 39,
	40, 41, 32, 33, 36, 37, 38, 39, 40, 41,
	31, 35, 34, 14, 145, 26, 29, 64, 71, 20,
	176, 70, 16, 26, 2, 182, 25, 171, 6, 46,
	44, 19, 4, 0, 25, 21, 74, 0, 0, 22,
	0, 0, 0, 23, 42, 33, 36, 37, 38, 39,
	40, 41, 42, 33, 36, 37, 38, 39, 40, 41,
	0, 0, 0, 0, 0, 26, 0, 0, 0, 20,
	0, 0, 0, 26, 0, 0, 25, 0, 0, 50,
	51, 55, 52, 53, 25, 54, 58, 59, 56, 57,
	60, 61, 0, 0, 42, 58, 59, 56, 57, 60,
	61, 180, 42, 0, 179, 50, 51, 55, 52, 53,
	0, 54, 58, 59, 56, 57, 60, 61, 0, 0,
	0, 0, 0, 0, 0, 50, 51, 55, 52, 53,
	192, 54, 58, 59, 56, 57, 60, 61, 0, 0,
	0, 0, 0, 0, 0, 50, 51, 55, 52, 53,
	120, 54, 58, 59, 56, 57, 60, 61, 0, 0,
	0, 50, 51, 55, 52, 53, 151, 54, 58, 59,
	56, 57, 60, 61, 0, 0, 0, 0, 20, 50,
	51, 55, 52, 53, 0, 54, 58, 59, 56, 57,
	60, 61, 52, 53, 0, 54, 58, 59, 56, 57,
	60, 61,
}

var GosPact = [...]int16{
	-28, -1000, -1000, 161, -1000, 194, -1000, -1000, 131, 8,
	6, -1000, -1000, -1000, -1000, 388, -1000, -1000, -1000, 139,
	211, 269, 261, 219, -1000, 269, 127, 16, 74, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 55, 35, 161, 123, 63, 58, 33, -1000, -1000,
	269, 269, 269, 269, 269, 269, 269, 269, 269, 269,
	269, 269, 157, -1000, 71, -1000, 370, 32, -1000, 370,
	1, 99, -1000, -1000, -1000, -18, 388, 334, -1000, -1000,
	-1000, 269, 138, 269, 269, 153, 269, 60, 193, 191,
	189, 182, 139, 398, 398, 297, 297, 297, 398, -1000,
	-1000, -1000, -1000, -1000, -1000, 172, 96, 269, 62, 83,
	90, -1000, -1000, -33, -1000, 269, -1000, 153, -1000, 269,
	-1000, 354, -1000, -14, 72, 72, 15, 4, -1000, 388,
	0, -1000, -1000, -1000, -1000, -1, -1000, 151, -1000, 269,
	72, 150, 146, 60, -15, -21, 388, -1000, 85, 15,
	388, -1000, 269, 140, -1000, 269, -1000, 269, 67, 139,
	-1000, 72, -1000, 89, -1000, -1000, -1000, 269, -2, -1000,
	288, 99, -1000, 82, -1000, 60, 99, -1000, -1000, -1000,
	269, -1000, -6, -16, -1000, 62, -1000, -1000, 314, -1000,
	60, -1000, -1000, -1000,
}

var GosPgo = [...]uint8{
	0, 252, 250, 249, 191, 248, 3, 4, 247, 245,
	244, 146, 18, 5, 242, 241, 240, 238, 2, 237,
	44, 11, 236, 0, 8, 172, 234, 6, 9, 233,
	232, 183, 231, 230, 222, 210, 208, 10, 1, 7,
	207, 204, 203,
}

var GosR1 = [...]int8{
	0, 41, 10, 10, 1, 2, 2, 2, 3, 3,
	11, 11, 11, 5, 7, 7, 7, 6, 8, 8,
	8, 8, 9, 9, 4, 4, 38, 38, 38, 38,
	34, 34, 34, 18, 19, 19, 12, 12, 12, 12,
	12, 12, 36, 36, 36, 31, 37, 33, 13, 13,
	13, 13, 13, 14, 14, 39, 39, 39, 40, 40,
	40, 40, 29, 29, 15, 16, 26, 42, 17, 20,
	20, 20, 21, 21, 30, 32, 35, 23, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 28, 28, 25, 25, 25, 25, 25, 22,
	22, 22, 22, 22, 27, 27, 27, 24,
}

var GosR2 = [...]int8{
	0, 1, 1, 2, 2, 1, 3, 3, 3, 3,
	0, 2, 2, 7, 0, 1, 3, 2, 0, 1,
	3, 3, 1, 3, 1, 3, 1, 3, 5, 3,
	4, 6, 8, 3, 1, 2, 2, 2, 1, 1,
	1, 1, 3, 5, 4, 3, 3, 4, 0, 1,
	1, 1, 1, 2, 2, 3, 5, 5, 2, 3,
	7, 3, 2, 3, 1, 1, 1, 0, 3, 1,
	1, 1, 1, 3, 4, 3, 6, 1, 3, 3,
	3, 3, 3, 3, 3, 2, 3, 3, 3, 3,
	3, 3, 1, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 0, 1, 3, 1,
}

var GosChk = [...]int16{
	-1000, -41, -10, -11, -1, 42, -5, -12, 41, -13,
	-36, -18, -39, -40, -29, -23, -14, -31, -37, 40,
	28, 44, 48, 52, -25, 35, 24, -20, -21, -22,
	-35, -33, -34, 4, -30, -32, 5, 6, 7, 8,
	9, 10, 53, -11, -2, 4, -3, 10, 37, 37,
	11, 12, 14, 15, 17, 13, 20, 21, 18, 19,
	22, 23, -4, 4, -19, -12, -23, -20, -18, -23,
	-15, -17, -13, -31, 37, -28, -23, -23, -25, 25,
	26, 31, 34, 30, 27, 33, 35, 35, 15, 34,
	15, 34, 35, -23, -23, -23, -23, -23, -23, -23,
	-23, -23, -23, -23, -23, 33, -38, 30, 4, 43,
	31, 29, -12, -18, -18, 37, -18, -42, 37, 33,
	36, -23, 4, 10, -28, -28, -20, -27, -24, -23,
	-38, 4, 4, 4, 4, -7, -6, -4, 4, 30,
	-28, 34, 31, 32, 45, -26, -23, -37, -21, -20,
	-23, 32, 35, 34, 36, 33, 36, 33, 36, 33,
	-38, -28, 4, 4, -38, -18, -39, 37, -27, -24,
	-23, -8, -38, 35, -6, 32, -16, -13, 36, 36,
	33, -18, -9, -7, -38, 4, -38, -18, -23, 36,
	33, 36, 36, -38,
}

var GosDef = [...]int8{
	10, -2, 1, -2, 10, 0, 11, 12, 0, 0,
	0, 38, 39, 40, 41, 49, 50, 51, 52, 0,
	48, 0, 48, 0, 77, 0, 0, -2, 0, 94,
	95, 97, 98, 69, 70, 71, 99, 100, 101, 102,
	103, 0, 0, -2, 4, 5, 0, 0, 36, 37,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 24, 48, 34, 0, 96, 58, 49,
	0, 0, 64, -2, 62, 0, 92, 0, 85, 53,
	54, 0, 0, 0, 0, 0, 104, 0, 0, 0,
	0, 0, 14, 79, 80, 81, 82, 83, 84, 86,
	87, 88, 89, 90, 91, 0, 42, 0, 26, 0,
	0, 33, 35, 55, 59, 0, 61, 0, 63, 0,
	78, 0, 75, 0, 45, 46, 73, 0, 105, 107,
	0, 7, 8, 6, 9, 0, 15, 0, 25, 0,
	44, 0, 0, 0, 0, 0, 66, 68, 0, 72,
	93, 74, 104, 0, 47, 0, 30, 0, 18, 0,
	17, 43, 27, 0, 29, 56, 57, 48, 0, 106,
	0, 0, 19, 14, 16, 0, 0, 65, 76, 31,
	0, 13, 0, 0, 22, -2, 28, 60, 0, 20,
	0, 21, 32, 23,
}

var GosTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 24, 3, 3, 3, 3, 3, 3,
	35, 36, 14, 11, 33, 12, 34, 15, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 38, 37,
	3, 30, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 31, 3, 32, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 28, 3, 29,
}

var GosTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 13,
	16, 17, 18, 19, 20, 21, 22, 23, 25, 26,
	27, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53,
}

var GosTok3 = [...]int8{
	0,
}

var GosErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	GosDebug        = 0
	GosErrorVerbose = false
)

type GosLexer interface {
	Lex(lval *GosSymType) int
	Error(s string)
}

type GosParser interface {
	Parse(GosLexer) int
	Lookahead() int
}

type GosParserImpl struct {
	lval  GosSymType
	stack [GosInitialStackSize]GosSymType
	char  int
}

func (p *GosParserImpl) Lookahead() int {
	return p.char
}

func GosNewParser() GosParser {
	return &GosParserImpl{}
}

const GosFlag = -1000

func GosTokname(c int) string {
	if c >= 1 && c-1 < len(GosToknames) {
		if GosToknames[c-1] != "" {
			return GosToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func GosStatname(s int) string {
	if s >= 0 && s < len(GosStatenames) {
		if GosStatenames[s] != "" {
			return GosStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func GosErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !GosErrorVerbose {
		return "syntax error"
	}

	for _, e := range GosErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + GosTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(GosPact[state])
	for tok := TOKSTART; tok-1 < len(GosToknames); tok++ {
		if n := base + tok; n >= 0 && n < GosLast && int(GosChk[int(GosAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if GosDef[state] == -2 {
		i := 0
		for GosExca[i] != -1 || int(GosExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; GosExca[i] >= 0; i += 2 {
			tok := int(GosExca[i])
			if tok < TOKSTART || GosExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if GosExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += GosTokname(tok)
	}
	return res
}

func Goslex1(lex GosLexer, lval *GosSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(GosTok1[0])
		goto out
	}
	if char < len(GosTok1) {
		token = int(GosTok1[char])
		goto out
	}
	if char >= GosPrivate {
		if char < GosPrivate+len(GosTok2) {
			token = int(GosTok2[char-GosPrivate])
			goto out
		}
	}
	for i := 0; i < len(GosTok3); i += 2 {
		token = int(GosTok3[i+0])
		if token == char {
			token = int(GosTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(GosTok2[1]) /* unknown char */
	}
	if GosDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", GosTokname(token), uint(char))
	}
	return char, token
}

func GosParse(Goslex GosLexer) int {
	return GosNewParser().Parse(Goslex)
}

func (Gosrcvr *GosParserImpl) Parse(Goslex GosLexer) int {
	var Gosn int
	var GosVAL GosSymType
	var GosDollar []GosSymType
	_ = GosDollar // silence set and not used
	GosS := Gosrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Gosstate := 0
	Gosrcvr.char = -1
	Gostoken := -1 // Gosrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Gosstate = -1
		Gosrcvr.char = -1
		Gostoken = -1
	}()
	Gosp := -1
	goto Gosstack

ret0:
	return 0

ret1:
	return 1

Gosstack:
	/* put a state and value onto the stack */
	if GosDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", GosTokname(Gostoken), GosStatname(Gosstate))
	}

	Gosp++
	if Gosp >= len(GosS) {
		nyys := make([]GosSymType, len(GosS)*2)
		copy(nyys, GosS)
		GosS = nyys
	}
	GosS[Gosp] = GosVAL
	GosS[Gosp].yys = Gosstate

Gosnewstate:
	Gosn = int(GosPact[Gosstate])
	if Gosn <= GosFlag {
		goto Gosdefault /* simple state */
	}
	if Gosrcvr.char < 0 {
		Gosrcvr.char, Gostoken = Goslex1(Goslex, &Gosrcvr.lval)
	}
	Gosn += Gostoken
	if Gosn < 0 || Gosn >= GosLast {
		goto Gosdefault
	}
	Gosn = int(GosAct[Gosn])
	if int(GosChk[Gosn]) == Gostoken { /* valid shift */
		Gosrcvr.char = -1
		Gostoken = -1
		GosVAL = Gosrcvr.lval
		Gosstate = Gosn
		if Errflag > 0 {
			Errflag--
		}
		goto Gosstack
	}

Gosdefault:
	/* default state action */
	Gosn = int(GosDef[Gosstate])
	if Gosn == -2 {
		if Gosrcvr.char < 0 {
			Gosrcvr.char, Gostoken = Goslex1(Goslex, &Gosrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if GosExca[xi+0] == -1 && int(GosExca[xi+1]) == Gosstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Gosn = int(GosExca[xi+0])
			if Gosn < 0 || Gosn == Gostoken {
				break
			}
		}
		Gosn = int(GosExca[xi+1])
		if Gosn < 0 {
			goto ret0
		}
	}
	if Gosn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Goslex.Error(GosErrorMessage(Gosstate, Gostoken))
			Nerrs++
			if GosDebug >= 1 {
				__yyfmt__.Printf("%s", GosStatname(Gosstate))
				__yyfmt__.Printf(" saw %s\n", GosTokname(Gostoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Gosp >= 0 {
				Gosn = int(GosPact[GosS[Gosp].yys]) + GosErrCode
				if Gosn >= 0 && Gosn < GosLast {
					Gosstate = int(GosAct[Gosn]) /* simulate a shift of "error" */
					if int(GosChk[Gosstate]) == GosErrCode {
						goto Gosstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if GosDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", GosS[Gosp].yys)
				}
				Gosp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if GosDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", GosTokname(Gostoken))
			}
			if Gostoken == GosEofCode {
				goto ret1
			}
			Gosrcvr.char = -1
			Gostoken = -1
			goto Gosnewstate /* try again in the same state */
		}
	}

	/* reduction by production Gosn */
	if GosDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Gosn, GosStatname(Gosstate))
	}

	Gosnt := Gosn
	Gospt := Gosp
	_ = Gospt // guard against "declared and not used"

	Gosp -= int(GosR2[Gosn])
	// Gosp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Gosp+1 >= len(GosS) {
		nyys := make([]GosSymType, len(GosS)*2)
		copy(nyys, GosS)
		GosS = nyys
	}
	GosVAL = GosS[Gosp+1]

	/* consult goto table to find next state */
	Gosn = int(GosR1[Gosn])
	Gosg := int(GosPgo[Gosn])
	Gosj := Gosg + GosS[Gosp].yys + 1

	if Gosj >= GosLast {
		Gosstate = int(GosAct[Gosg])
	} else {
		Gosstate = int(GosAct[Gosj])
		if int(GosChk[Gosstate]) != -Gosn {
			Gosstate = int(GosAct[Gosg])
		}
	}
	// dummy call; replaced with literal code
	switch Gosnt {

	case 1:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			Goslex.(*GosLex).File = GosDollar[1].File
		}
	case 2:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.File = File{pckg: "", parts: GosDollar[1].fileContents, pos: Goslex.(*GosLex).Pos}
		}
	case 3:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.File = File{pckg: GosDollar[1].val, parts: GosDollar[2].fileContents, pos: Goslex.(*GosLex).Pos}
		}
	case 4:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.val = GosDollar[2].val
		}
	case 5:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.val = GosDollar[1].val
		}
	case 6:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.val = GosDollar[1].val + "/" + GosDollar[3].val
		}
	case 7:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.val = GosDollar[1].val + "/" + GosDollar[3].val
		}
	case 8:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.val = GosDollar[1].val + "." + GosDollar[3].val
		}
	case 9:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.val = GosDollar[1].val + "." + GosDollar[3].val
		}
	case 10:
		GosDollar = GosS[Gospt-0 : Gospt+1]
		{
			GosVAL.fileContents = []any{}
		}
	case 11:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.fileContents = append(GosDollar[1].fileContents, GosDollar[2].fn)
		}
	case 12:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.fileContents = append(GosDollar[1].fileContents, GosDollar[2].statement)
		}
	case 13:
		GosDollar = GosS[Gospt-7 : Gospt+1]
		{
			GosVAL.fn = &function{name: GosDollar[2].val, args: GosDollar[4].args, ret: GosDollar[6].args, body: GosDollar[7].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 14:
		GosDollar = GosS[Gospt-0 : Gospt+1]
		{
			GosVAL.args = []*varDef{}
		}
	case 15:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.args = []*varDef{GosDollar[1].arg}
		}
	case 16:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.args = append(GosDollar[1].args, GosDollar[3].arg)
		}
	case 17:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.arg = &varDef{names: GosDollar[1].vals, tip: GosDollar[2].typeRef, pos: Goslex.(*GosLex).Pos}
		}
	case 18:
		GosDollar = GosS[Gospt-0 : Gospt+1]
		{
			GosVAL.args = []*varDef{}
		}
	case 19:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.args = []*varDef{&varDef{tip: GosDollar[1].typeRef, pos: Goslex.(*GosLex).Pos}}
		}
	case 20:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.args = GosDollar[2].args
		}
	case 21:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.args = GosDollar[2].args
		}
	case 22:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.args = []*varDef{&varDef{tip: GosDollar[1].typeRef, pos: Goslex.(*GosLex).Pos}}
		}
	case 23:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.args = append(GosDollar[1].args, &varDef{tip: GosDollar[3].typeRef, pos: Goslex.(*GosLex).Pos})
		}
	case 24:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.vals = []string{GosDollar[1].val}
		}
	case 25:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.vals = append(GosDollar[1].vals, GosDollar[3].val)
		}
	case 26:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.typeRef = &typeRef{name: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 27:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.typeRef = &typeRef{pckg: GosDollar[1].val, name: GosDollar[3].val, pos: Goslex.(*GosLex).Pos}
		}
	case 28:
		GosDollar = GosS[Gospt-5 : Gospt+1]
		{
			GosVAL.typeRef = &typeRef{mapKey: GosDollar[3].val, elem: GosDollar[5].typeRef, pos: Goslex.(*GosLex).Pos}
		}
	case 29:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.typeRef = &typeRef{elem: GosDollar[3].typeRef, pos: Goslex.(*GosLex).Pos}
		}
	case 30:
		GosDollar = GosS[Gospt-4 : Gospt+1]
		{
			GosVAL.funcCall = &funcCall{name: "map", returnTypes: []*typeRef{GosDollar[3].typeRef}, convertTo: runtime.VarKind(-1), pos: Goslex.(*GosLex).Pos}
		}
	case 31:
		GosDollar = GosS[Gospt-6 : Gospt+1]
		{
			GosVAL.funcCall = &funcCall{name: "map", params: []*expression{GosDollar[5].expression}, returnTypes: []*typeRef{GosDollar[3].typeRef}, convertTo: runtime.VarKind(-1), pos: Goslex.(*GosLex).Pos}
		}
	case 32:
		GosDollar = GosS[Gospt-8 : Gospt+1]
		{
			GosVAL.funcCall = &funcCall{name: "map", params: []*expression{GosDollar[5].expression, GosDollar[7].expression}, returnTypes: []*typeRef{GosDollar[3].typeRef}, convertTo: runtime.VarKind(-1), pos: Goslex.(*GosLex).Pos}
		}
	case 33:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindBlock, stmt: GosDollar[2].statements, pos: Goslex.(*GosLex).Pos}
		}
	case 34:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statements = []*statement{GosDollar[1].statement}
		}
	case 35:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.statements = append(GosDollar[1].statements, GosDollar[2].statement)
		}
	case 36:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.statement = GosDollar[1].statement
		}
	case 37:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindVar, stmt: GosDollar[1].varDef, pos: Goslex.(*GosLex).Pos}
		}
	case 38:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = GosDollar[1].statement
		}
	case 39:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindIf, stmt: GosDollar[1].ifStatement, pos: Goslex.(*GosLex).Pos}
		}
	case 40:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindFor, stmt: GosDollar[1].forStatement, pos: Goslex.(*GosLex).Pos}
		}
	case 41:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindRet, stmt: GosDollar[1].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 42:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.varDef = &varDef{names: GosDollar[2].vals, tip: GosDollar[3].typeRef, pos: Goslex.(*GosLex).Pos}
		}
	case 43:
		GosDollar = GosS[Gospt-5 : Gospt+1]
		{
			GosVAL.varDef = &varDef{names: GosDollar[2].vals, tip: GosDollar[3].typeRef, init: GosDollar[5].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 44:
		GosDollar = GosS[Gospt-4 : Gospt+1]
		{
			GosVAL.varDef = &varDef{names: GosDollar[2].vals, init: GosDollar[4].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 45:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.assignment = &assignment{left: GosDollar[1].lvList, right: GosDollar[3].expressions, pos: Goslex.(*GosLex).Pos}
			for _, lv := range GosDollar[1].lvList {
				lv.forAssignment = true
			}
		}
	case 46:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.varDef = &varDef{lvalues: GosDollar[1].lvList, init: GosDollar[3].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 47:
		GosDollar = GosS[Gospt-4 : Gospt+1]
		{
			GosVAL.funcCall = &funcCall{name: GosDollar[1].val, params: GosDollar[3].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 48:
		GosDollar = GosS[Gospt-0 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindEmpty, pos: Goslex.(*GosLex).Pos}
		}
	case 49:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindExpression, stmt: GosDollar[1].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 50:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = GosDollar[1].statement
		}
	case 51:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindAssign, stmt: GosDollar[1].assignment, pos: Goslex.(*GosLex).Pos}
		}
	case 52:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindInit, stmt: GosDollar[1].varDef, pos: Goslex.(*GosLex).Pos}
		}
	case 53:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindInc, stmt: GosDollar[1].lvalue, pos: Goslex.(*GosLex).Pos}
		}
	case 54:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindDec, stmt: GosDollar[1].lvalue, pos: Goslex.(*GosLex).Pos}
		}
	case 55:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.ifStatement = &ifStatement{condition: GosDollar[2].expression, thn: GosDollar[3].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 56:
		GosDollar = GosS[Gospt-5 : Gospt+1]
		{
			GosVAL.ifStatement = &ifStatement{condition: GosDollar[2].expression, thn: GosDollar[3].statement, els: GosDollar[5].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 57:
		GosDollar = GosS[Gospt-5 : Gospt+1]
		{
			GosVAL.ifStatement = &ifStatement{condition: GosDollar[2].expression, thn: GosDollar[3].statement, els: &statement{kind: stmtKindIf, stmt: GosDollar[5].ifStatement, pos: Goslex.(*GosLex).Pos}}
		}
	case 58:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.forStatement = &forStatement{block: GosDollar[2].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 59:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.forStatement = &forStatement{condition: GosDollar[2].expression, block: GosDollar[3].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 60:
		GosDollar = GosS[Gospt-7 : Gospt+1]
		{
			GosVAL.forStatement = &forStatement{condition: GosDollar[4].expression, initStmt: GosDollar[2].statement, postStmt: GosDollar[6].statement, block: GosDollar[7].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 61:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.forStatement = &forStatement{rangeStmt: GosDollar[2].statement, block: GosDollar[3].statement, pos: Goslex.(*GosLex).Pos}
		}
	case 62:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.expressions = []*expression(nil)
		}
	case 63:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expressions = GosDollar[2].expressions
		}
	case 64:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = GosDollar[1].statement
		}
	case 65:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = GosDollar[1].statement
		}
	case 66:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expression = GosDollar[1].expression
		}
	case 67:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindAssign, stmt: GosDollar[1].assignment, pos: Goslex.(*GosLex).Pos}
		}
	case 68:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.statement = &statement{kind: stmtKindInit, stmt: GosDollar[1].assignment, pos: Goslex.(*GosLex).Pos}
		}
	case 69:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.lvalue = &lvalue{kind: lvalueKindIdent, stmt: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 70:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.lvalue = &lvalue{kind: lvalueKindIndex, stmt: GosDollar[1].arrayAccess, pos: Goslex.(*GosLex).Pos}
		}
	case 71:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.lvalue = &lvalue{kind: lvalueKindField, stmt: GosDollar[1].fieldAccess, pos: Goslex.(*GosLex).Pos}
		}
	case 72:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.lvList = []*lvalue{GosDollar[1].lvalue}
		}
	case 73:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.lvList = append(GosDollar[1].lvList, GosDollar[3].lvalue)
		}
	case 74:
		GosDollar = GosS[Gospt-4 : Gospt+1]
		{
			GosVAL.arrayAccess = &arrayAccess{lvalue: GosDollar[1].lvalue, expression: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 75:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.fieldAccess = &fieldAccess{lvalue: GosDollar[1].lvalue, field: GosDollar[3].val, pos: Goslex.(*GosLex).Pos}
		}
	case 76:
		GosDollar = GosS[Gospt-6 : Gospt+1]
		{
			GosVAL.methodCall = &methodCall{lvalue: GosDollar[1].lvalue, name: GosDollar[3].val, params: GosDollar[5].expressions, pos: Goslex.(*GosLex).Pos}
		}
	case 77:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expression = GosDollar[1].expression
		}
	case 78:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindParens, left: GosDollar[2].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 79:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindSum, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 80:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindSub, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 81:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindMul, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 82:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindDiv, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 83:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindAnd, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 84:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindOr, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 85:
		GosDollar = GosS[Gospt-2 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindNot, left: GosDollar[2].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 86:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindEqualTo, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 87:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindNotEqualTo, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 88:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindGreaterThan, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 89:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindLessThan, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 90:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindGreaterThanOrEqualTo, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 91:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindLessThanOrEqualTo, left: GosDollar[1].expression, right: GosDollar[3].expression, pos: Goslex.(*GosLex).Pos}
		}
	case 92:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expressions = []*expression{GosDollar[1].expression}
		}
	case 93:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expressions = append(GosDollar[1].expressions, GosDollar[3].expression)
		}
	case 94:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindConst, left: GosDollar[1].constant, pos: Goslex.(*GosLex).Pos}
		}
	case 95:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			{
				GosVAL.expression = &expression{kind: expressionKindMethod, left: GosDollar[1].methodCall, pos: Goslex.(*GosLex).Pos}
			}
		}
	case 96:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expression = &expression{kind: expressionKindLValue, left: GosDollar[1].lvalue, pos: Goslex.(*GosLex).Pos}
		}
	case 97:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			{
				GosVAL.expression = &expression{kind: expressionKindFunc, left: GosDollar[1].funcCall, pos: Goslex.(*GosLex).Pos}
			}
		}
	case 98:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			{
				GosVAL.expression = &expression{kind: expressionKindFunc, left: GosDollar[1].funcCall, pos: Goslex.(*GosLex).Pos}
			}
		}
	case 99:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.constant = &constant{kind: constKindInt, value: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 100:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.constant = &constant{kind: constKindFloat, value: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 101:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.constant = &constant{kind: constKindChar, value: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 102:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.constant = &constant{kind: constKindString, value: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 103:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.constant = &constant{kind: constKindBool, value: GosDollar[1].val, pos: Goslex.(*GosLex).Pos}
		}
	case 104:
		GosDollar = GosS[Gospt-0 : Gospt+1]
		{
			GosVAL.expressions = []*expression{}
		}
	case 105:
		GosDollar = GosS[Gospt-1 : Gospt+1]
		{
			GosVAL.expressions = []*expression{GosDollar[1].expression}
		}
	case 106:
		GosDollar = GosS[Gospt-3 : Gospt+1]
		{
			GosVAL.expressions = append(GosDollar[1].expressions, GosDollar[3].expression)
		}
	}
	goto Gosstack /* stack new state and value */
}
